name: Build The Skypark

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore dependencies
        run: nuget restore Packager/Packager.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build The Skypark
        run: msbuild Packager/Packager.sln /p:Configuration=Release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TheSkypark
          path: Packager/bin/Release/
